# Generated by Django 3.2.15 on 2022-11-12 22:50

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import website.utils.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_create_main_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(template='components/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(template='components/blocks/paragraph_block.html')), ('image', website.utils.blocks.ImageWithCaptionBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock(required=True)), ('language', wagtail.blocks.CharBlock(required=False))])), ('image_text', wagtail.blocks.StructBlock([('image', website.utils.blocks.ImageWithCaptionBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))])), ('cards', wagtail.blocks.StructBlock([('card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.blocks.URLBlock(required=False))], required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
