# Generated by Django 3.2.15 on 2022-11-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('home', '0005_create_card_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='listing_summary',
            field=models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='listing_title',
            field=models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255),
        ),
    ]
