# Generated by Django 3.2.15 on 2022-11-19 17:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import website.utils.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(template='components/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(template='components/blocks/paragraph_block.html')), ('image', website.utils.blocks.ImageWithCaptionBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock(required=True)), ('language', wagtail.blocks.CharBlock(required=False))])), ('image_text', wagtail.blocks.StructBlock([('image', website.utils.blocks.ImageWithCaptionBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))])), ('cards', wagtail.blocks.StructBlock([('card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.blocks.URLBlock(required=False))], required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], use_json_field=True)),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Blog Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(template='components/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(template='components/blocks/paragraph_block.html')), ('image', website.utils.blocks.ImageWithCaptionBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock(required=True)), ('language', wagtail.blocks.CharBlock(required=False))])), ('image_text', wagtail.blocks.StructBlock([('image', website.utils.blocks.ImageWithCaptionBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')]))])), ('cards', wagtail.blocks.StructBlock([('card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True)), ('link', wagtail.blocks.StructBlock([('internal_link', wagtail.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.blocks.URLBlock(required=False))], required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Blog Index Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
